apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: wod_db
            - name: POSTGRES_USER
              value: cyril
            - name: POSTGRES_PASSWORD
              value: gigapassword
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: postgres-config
          hostPath:
            path: docker/db/config/wod_db.conf
